name: Release Creation

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: mkdir ./Release

    - run: move "./Plugin/com.cdeenen.materialdeck.sdPlugin" "./com.cdeenen.materialdeck.sdPlugin"

    - name: StreamDeck Distribution Tool
      uses: AdamCarballo/streamdeck-distribution-tool@v1
      with:
        input: com.cdeenen.materialdeck.sdPlugin
        output: Release

    # Update release
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.unpublished }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './Release/com.cdeenen.materialdeck.streamDeckPlugin, ./Profiles/*.streamDeckProfile'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}